version: "3.8"
services:
  app:
    build:
      args:
        user: SF
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: delay-system
    container_name: delay-system-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - delay-net

  db:
    image: mysql:latest
    container_name: delay-system-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: delay-system-mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - delay-net

  nginx:
    image: nginx:alpine
    container_name: delay-system-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - delay-net

networks:
  delay-net:
    driver: bridge